"""
Specifies configuration variables
"""
#######################
# Data Configurations #
#######################

# Relative directory location of data
RELATIVE_DATA_DIR = "data/tsv_files"

# Timestamp column title
TIMESTAMP_COL_TITLE = 'RecordingTimestamp'

# Name of the column of the X coordinates of the gaze
# points as specified in the .tsv files
X_GAZE_COL_TITLE = 'GazePointX (ADCSpx)'

# Name of the column of the Y coordinates of the gaze
# points as specified in the .tsv files
Y_GAZE_COL_TITLE = 'GazePointY (ADCSpx)'

# Name of the column of the X coordinates of the fixation
# points as specified in the .tsv files
X_FIXATION_COL_TITLE = 'FixationPointX (MCSpx)'

# Name of the column of the Y coordinates of the fixation
# points as specified in the .tsv files
Y_FIXATION_COL_TITLE = 'FixationPointY (MCSpx)'

# Name of the column of the X displacement of stimulus image
STIMULUS_X_DISPLACEMENT_COL_TITLE = 'MediaPosX (ADCSpx)'

# Name of the column of the Y displacement of stimulus image
STIMULUS_Y_DISPLACEMENT_COL_TITLE = 'MediaPosY (ADCSpx)'

# Name of the column with the stimuli names
STIMULUS_COL_TITLE = 'MediaName'

PARTICIPANT_NAME_COL_TITLE = 'ParticipantName'

# Name of the column with the participant filename
# (generated by this application)
PARTICIPANT_FILENAME_COL_TITLE = 'participant_filename'

#########################
# Figure Configurations #
#########################

# Choose an integer value
# from 1 to higher integers
# for the plot height. Higher
# numbers correspond to a larger
# plot height
PLT_HEIGHT = 7

# Maximum and minimum values of each axis in a
# figure will be set beyond the extrema values within
# the data set along said axis; the buffer will
# be calculated as a percentage, namely
# EXTREMA_BUFFER_PCT, of extrema values.
EXTREMA_BUFFER_PCT = 0.05

MAX_FIXATION_PT_SIZE = 50

DEFAULT_EPS_VALUE = 22

DEFAULT_MIN_SAMPLES_VALUE = 10

DEFAULT_SUPPORT_THRESHOLD = 0

DEFAULT_FORWARD_CONFIDENCE_THRESHOLD = 50

DEFAULT_BACKWARD_CONFIDENCE_THRESHOLD = 50

########################
# Image Configurations #
########################

# Relative directory location of images
RELATIVE_STIMULUS_IMAGE_DIR = "data/stimuli"

# Name of stimuli to exclude from the stimuli
# that can be visualized.
EXCLUDE_STIMULI_LIST = ['nan', 'Instruction Element']

MAKE_IMG_GRAYSCALE = True
